### ISSUE TITLE
Set up GitHub Actions to run tests

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/covid-19-procurement-explorer-public#166]

**Comment by jpmckinney** [comment]
@KushalRaj Are there no tests?

**Comment by KushalRaj** [comment]
Currently we have not written any test in this project. We are planning to write test for basic coverage after we complete the core functionality and bug fixing.

**Comment by jpmckinney** [comment]
I suspect that no tests will be written, so closing.
