### ISSUE TITLE
Redirect from apex domain to www

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/covid-19-procurement-explorer-public#183]
The deploy repo has now been configured to serve both, using the same virtual host. However, www. should be the canonical URL.

**Comment by KushalRaj** [comment]
Please elaborate more on this issue.

**Comment by jpmckinney** [comment]
Closed via https://github.com/open-contracting/deploy/commit/3f5339527c9eeb91ac538e308af81f7b1834f2e0
