### ISSUE TITLE
Address dependabot alerts by updating dependencies

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/covid-19-procurement-explorer-public#319]
https://github.com/open-contracting/covid-19-procurement-explorer-public/security/dependabot

**Comment by KushalRaj** [comment]
@jpmckinney There are none dependabot suggestion currently. This issue can be closed.

**Comment by jpmckinney** [comment]
@KushalRaj hmm, maybe only admins can see. The warnings are:

![B5763BAB-8C4F-441A-AD9E-ED6EB4FCDA3A](https://user-images.githubusercontent.com/26463/114867050-51693e00-9dc2-11eb-8b71-1726bd15c695.png)

**Comment by jpmckinney** [comment]
We will accept the security risk.
