### ISSUE TITLE
Clean up eslintConfig in package.json

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/covid-19-procurement-explorer-public#322]
package.json has:

```json
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
```

but if I put those in `.eslintrc.js` I get `Cannot find module 'typescript'`

My assumption is we aren't using this configuration in `package.json`, and it should be deleted.

**Comment by KushalRaj** [comment]
These lines are removed
