### ISSUE TITLE
Remove unused files

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/covid-19-procurement-explorer-public#339]
I don't think these are used:

* src/assets/img/country-flags/
* src/assets/img/data-providers/
* src/assets/img/mexicana.svg
* src/assets/img/news-detail.jpg
* src/assets/img/news.jpg
* src/store/static-data/equities.json

**Comment by jpmckinney** [comment]
Why is this closed? I still see the files in the `main` branch. If there is a reason to keep them, please explain.

**Comment by KushalRaj** [comment]
These files have been removed in a branch I am currently working on. Changes will be reflected after i merge it. I forgot and closed the branch first before sending the changes.

**Comment by KushalRaj** [comment]
This files have been removed.
