### ISSUE TITLE
Overall summary table additional columns

### ISSUE THREAD

**Issue by KushalRaj** [open-contracting/covid-19-procurement-explorer-public#381]
- [x] No of Buyers
- [x] No of Suppliers
- [ ] Average bids per contract
- [ ] Monopolization
- [ ] quantity of red flags
- [ ] total value of contracts with red flags
- [ ] quantity of equity contracts
- [ ] total value of equity contracts
- [ ] total value per product category
- [x] Time span
- [x] GDP per captia
- [x] healthcare budget
- [x] % of GDP to healthcare budget
- [ ] $ per covid case
- [ ] Covid statistics per country Active cases, current
- [x] Covid statistics per country Total cases
- [x] Total death cases, cumulative

**Comment by jpmckinney** [comment]
I assume that this feature will not be implemented, at this point, so closing.
